

services:
  db:
    image: postgres:16
    container_name: wb-db
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped

volumes:
  pg_data:

networks:
  mynetwork:
    external: true